openapi: 3.0.4
info:
  title: SBT Minting API
  description: API to mint soul-bound tokens (SBTs) on an Ethereum-compatible blockchain.
  version: 0.1.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /claim:
    post:
      summary: Claim an SBT for given address
      description: |
        Claim an SBT for given address.
        The `to` address is of the wallet that will receive the SBT.
        The claim will be authorized with `signature`, which is the `to` wallet signature of `to` address string.
      parameters:
        - name: to
          in: query
          required: true
          schema:
            type: string
          description: Ethereum address to claim the SBT to
          example: "0x0000000000000000000000000000000000000001"
        - name: signature
          in: query
          required: true
          schema:
            type: string
          description: `to` wallet signature of `to` address string
          example: "0x1a32da8189e96c52b1f9a1fdb8cf81ca369236fc4041f85d23fcd08eaad118e97182b8836ea2813b2c779feca296c4eae21453ef1e5f3f6705cc3845d9c549f31c"
      responses:
        "200":
          description: SBT claim submitted successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - txHash
                properties:
                  txHash:
                    type: string
                    description: Hash of the SBT minting transaction

  /status:
    get:
      summary: Get SBT state
      description: Get SBT state by its minting transaction hash
      parameters:
        - name: txHash
          in: query
          required: true
          schema:
            type: string
          description: Hash of the SBT minting transaction created by the claim API
          example: "0x1234567890123456789012345678901234567890"
      responses:
        "200":
          description: SBT state
          content:
            application/json:
              schema:
                type: object
                required:
                  - txHash
                  - from
                  - to
                  - createdAt
                  - updatedAt
                  - status
                properties:
                  txHash:
                    type: string
                    description: Hash of the SBT minting transaction
                  from:
                    type: string
                    description: Ethereum address that submitted the SBT minting transaction
                  to:
                    type: string
                    description: Ethereum address that will receive the SBT
                  tokenId:
                    type: number
                    description: Token ID of the SBT
                  tokenUri:
                    type: string
                    description: URI of the SBT metadata
                  tokenData:
                    type: object
                    description: Metadata of the SBT (if encoded in the URI as JSON)
                  createdAt:
                    type: string
                    description: ISO 8601 timestamp of when the SBT minting transaction was submitted to the network
                  issuedAt:
                    type: string
                    description: ISO 8601 timestamp of when the SBT was successfully issued
                  updatedAt:
                    type: string
                    description: ISO 8601 timestamp of last SBT state update
                  status:
                    type: string
                    description: Status of the SBT
                    enum:
                      - pending
                      - confirmed
                      - failed
